# Generated by Django 5.0.7 on 2024-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_parcel_locker_alter_parcel_open_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='order_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='order datetime'),
        ),
    ]
